#pragma once
#include <stddef.h>
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif
void GoblinKittySelect(int id);
void GoblinKittyClose(int id);
void GoblinKittyFeedSession(int id, const char* bytes, size_t size);
size_t GoblinKittyTakeSessionInput(int id, char* bytes, size_t capacity);
void GoblinKittyFeed(const char* bytes, size_t size);
void GoblinKittyReset(void);
// Replies generated by the terminal parser are delivered to the guest PTY.
size_t GoblinKittyTakeInput(char* bytes, size_t capacity);
typedef struct {
    uint32_t sprite, foreground, background, decoration, attributes;
} GoblinCell;
// GLES adapter, called with the engine lock held on the GLSurfaceView thread.
void GoblinRenderReset(void);
void GoblinRenderClearSprites(void);
void GoblinRenderSprite(unsigned x, unsigned y, unsigned z, const void* data, size_t size);
void GoblinRenderFrame(const GoblinCell* cells, unsigned rows, unsigned columns,
                      unsigned cell_width, unsigned cell_height, unsigned atlas_columns,
                      unsigned atlas_rows, int cursor_x, int cursor_y, int width, int height);
#ifdef __cplusplus
}
#endif
